# K-means
Phân cụm là một bài toán học không được giám sát, thường được sử dụng khi bạn không có nhãn dữ liệu. 

Phân cụm K-Means là một trong những thuật toán phân cụm phổ biến. Mục tiêu của thuật toán này là tìm các nhóm (các cụm) trong các dữ liệu nhất định. 

Xây dựng phân cụm KMeans được thực hiện theo ý tưởng sau:
- Chọn ra k tâm ngẫu nhiên của các cụm.
- Gán mỗi dữ liệu $x_i$ vào cụm có tâm gần nó nhất, bằng cách tính khoảng cách từ $x_i$ đến các tâm
- Chọn lại tâm cụm bằng cách tính lại tâm nhờ các điểm thuộc cụm
- Lặp lại các bước trên cho đến khi không có sự thay đổi về các điểm trong cụm.

Trong bài này chúng ta sẽ thực hiện cài đặt thuật toán phân cụm K-means từ đầu.

![title](https://i.imgur.com/k4XcapI.gif)

In [13]:
# Import một số thư viện cần thiết.
import random
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split 
import matplotlib.pyplot as plt

# Sử dụng một mẹo nhỏ để vẽ hình trên cùng một dòng thay vì mở cửa sổ mới
%matplotlib inline
plt.rcParams['figure.figsize'] = (10.0, 8.0) # đặt kích thước mặc định cho hình
plt.rcParams['image.interpolation'] = 'nearest'
plt.rcParams['image.cmap'] = 'gray'

# Một mẹo nhỏ để notebook tự load lại các module bên ngoài;
# xem thêm tại http://stackoverflow.com/questions/1907993/autoreload-of-modules-in-ipython
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [14]:
# Tải dữ liệu hoa cẩm chướng từ Scikit-learn.
iris = datasets.load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris.data, \
                                                    iris.target, test_size=0.2)

# In ra kích thước dữ liệu huấn luyện và dữ liệu kiểm tra như một 
# phép thử đơn giản.
print('Training data shape: ', X_train.shape)
print('Training labels shape: ', y_train.shape)
print('Test data shape: ', X_test.shape)
print('Test labels shape: ', y_test.shape)


('Training data shape: ', (120, 4))
('Training labels shape: ', (120,))
('Test data shape: ', (30, 4))
('Test labels shape: ', (30,))


Đầu tiên, chúng ta cần cài đặt hàm huấn luyện mô hình K-means. Trong phần này, K-means thực hiện việc học cách phân cụm dữ liệu từ dữ liệu huấn luyện.

Như đã nêu ở trên, việc học cách phân cụm được thực hiện theo 4 bước:
- Chọn ra k tâm ngẫu nhiên của các cụm.
- Gán mỗi dữ liệu $x_i$ vào cụm có tâm gần nó nhất, bằng cách tính khoảng cách từ $x_i$ đến các tâm
- Chọn lại tâm cụm bằng cách tính lại tâm nhờ các điểm thuộc cụm
- Lặp lại các bước trên cho đến khi không có sự thay đổi về các điểm trong cụm.

** Bài tập: ** Mở tệp `k_means.py` và cài đặt hàm `train()`. Trong phần này, để tiện tính toán, ta cài đặt đồng thời các hàm `compute_distances`.

*Gợi ý: Tham khảo K-Nearest Neighbor để cài đặt các hàm compute_distances.* 

In [15]:
from k_means import KMeans

# Khởi tạo bộ phân cụm KMeans. 
# Chọn số lượng các cụm cần phân ra, trong trường hợp này, ta chọn số cụm
# bằng số lượng các loại hoa cẩm chướng
cluster = KMeans(num_clusters=3)

# Mở tệp k_means.py và cài đặt hàm huấn luyện train().
cluster.train(X_train)

Initial centroids
[array([5.1, 2.5, 3. , 1.1]), array([6.2, 2.8, 4.8, 1.8]), array([5.6, 3. , 4.5, 1.5])]
New centroids 
[[5.05555556 3.32       1.74       0.35777778]
 [6.52363636 2.94909091 5.28181818 1.86363636]
 [5.7        2.75       4.19       1.3       ]]
New centroids 
[[5.0025641  3.44358974 1.47179487 0.24615385]
 [6.58333333 2.98541667 5.38333333 1.925     ]
 [5.73333333 2.6969697  4.14545455 1.29090909]]
New centroids 
[[5.0025641  3.44358974 1.47179487 0.24615385]
 [6.59777778 2.99555556 5.43333333 1.95555556]
 [5.78611111 2.70833333 4.18611111 1.30555556]]
New centroids 
[[5.0025641  3.44358974 1.47179487 0.24615385]
 [6.63571429 3.01190476 5.47857143 1.96904762]
 [5.80769231 2.71282051 4.23333333 1.34102564]]
New centroids 
[[5.0025641  3.44358974 1.47179487 0.24615385]
 [6.66410256 3.02307692 5.53076923 1.99487179]
 [5.84047619 2.72380952 4.27380952 1.36190476]]
New centroids 
[[5.0025641  3.44358974 1.47179487 0.24615385]
 [6.74857143 3.05142857 5.58571429 2.01714286]


In [16]:
# Bây giờ, cài đặt hàm predict_labels và chạy code dưới đây:
# Chúng ta dùng k = 3 (Số lượng cụm ứng với các nhãn cần phân biệt).
num_test = X_test.shape[0]
dists = cluster.compute_distances_no_loops(X_test)
y_test_pred = cluster.predict_labels(dists)

# Tính ra in ra tỉ lệ những ví dụ dự đoán đúng
num_correct = np.sum(y_test_pred == y_test)
accuracy = float(num_correct) / num_test
print('Got %d / %d correct => accuracy: %f' % (num_correct, num_test, accuracy))
print y_test_pred
print y_test

Got 14 / 30 correct => accuracy: 0.466667
[2 0 1 1 0 2 2 1 1 0 0 0 0 1 1 0 0 0 1 2 0 2 2 0 1 2 1 2 2 2]
[1 0 2 1 0 1 1 2 2 0 0 0 0 2 2 0 0 0 2 1 0 1 2 0 2 2 2 1 1 1]


** Bài tập: ** Điều chỉnh code để sau khi phân cụm, nhãn phân cụm trả về là nhãn tương ứng với loại hoa cẩm chướng của cụm đó.

In [17]:
import itertools

In [18]:
per = list(itertools.permutations([0, 1, 2]))
def acc(y_, y):
    for i in per:
        i = np.array(i)
        y_ = i[y_]
        num_correct = np.sum(y_ == y)
        accuracy = float(num_correct) / len(y)
        print('Got %d / %d correct => accuracy: %f' % (num_correct, num_test, accuracy))
acc(y_test_pred, y_test)

Got 14 / 30 correct => accuracy: 0.466667
Got 27 / 30 correct => accuracy: 0.900000
Got 8 / 30 correct => accuracy: 0.266667
Got 8 / 30 correct => accuracy: 0.266667
Got 8 / 30 correct => accuracy: 0.266667
Got 2 / 30 correct => accuracy: 0.066667
